### ISSUE TITLE
[QUESTION] Use of venv and dev deps installation

### ISSUE THREAD

**Issue by chandrasekharan98** [matakanobu/python-monorepo#1]
Hello, I arrived at this repo through your [article in Medium](https://medium.com/@mtakanobu2/python-monorepo-centralizing-multiple-projects-and-sharing-code-3c1ab496340a) and this has been really insightful, thank you for that!

After skimming the repo, I have a couple of questions
1. Though it isn't explicitly mentioned, I assume that a virtual environment is used. In this case do we create a venv and install deps (with `make deps`) for each project we work with? (i.e. 1 venv per project residing in the package's root)
2. How are dev dependencies (linter, formatter .etc.) installed when we run `make deps` for a project?
3. Do we intentionally specify the dev dependencies at the repository root alone and not specify it within each individual project?

Thanks in advance!

**Comment by matakanobu** [comment]
Hello,Thank you for reading my Medium article and checking out the repo. I'm glad you found it insightful.

>1. Though it isn't explicitly mentioned, I assume that a virtual environment is used. In this case do we create a venv and install deps (with make deps) for each project we work with? (i.e. 1 venv per project residing in the package's root)

Yes, that's correct. We anticipate setting up a virtual environment using "poetry" for each project and working within those environments.

>2.How are dev dependencies (linter, formatter .etc.) installed when we run make deps for a project?

This might be a bit tricky.
First, at the repository root, execute the following to install the dev dependencies:

```shell
poetry shell
poetry install
```

Then, move to the specific project you want to work on and install its dependencies:

```shell
cd projects/project-a
poetry install
```
That's it.

However, please note that the formatter and linter settings written in the pyproject.toml at the repository root might not apply. So that's a challenge.

Also, when working on a different project, be aware that you need to create a new virtual environment from the repository root again.

>3. Do we intentionally specify the dev dependencies at the repository root alone and not specify it within each individual project?

This approach is based on 2. Due to the current specifications of poetry, there doesn't seem to be a feature to inherit from a parent directory pyproject.toml. To achieve this, we'd need to prepare a script, which might complicate things. Of course, specifying dev dependencies in each project, as you mentioned, is a viable option. In my opinion, the formatter, linter, and testing framework should be common throughout the repository. However, some projects may have different python versions, so unification may not be easy.
